FROM php:8.2.3-fpm-alpine

# PHP config
COPY ./docker/php/php.ini /usr/local/etc/php/conf.d/php.ini

# Install required extensions
RUN apk add --no-cache \
    php-pcntl \
    libzip-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    nodejs \
    npm \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install fileinfo \
    && docker-php-ext-install zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd \
    && docker-php-ext-install pcntl \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    
# Set the working directory
WORKDIR /var/www/html

