version: "3"

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8090:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    container_name: docker_nginx
    networks:
      - laravel
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: docker_php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: docker_mysql
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: docker_laravel
      MYSQL_USER: docker_laravel_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
         - db_data:/var/lib/mysql
    networks:
      - laravel
  
  redis:
    image: redis:alpine
    container_name: docker_redis
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"
    networks:
      - laravel
  
  # node:
  #   image: node:latest
  #   container_name: docker_node
  #   volumes:
  #     - ./app:/app
  #   working_dir: /app
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   networks:
  #      - laravel
volumes:
    db_data: {}
